image: registry.gitlab.com/luwjistik1/gitlabci:v2.0

services:
  - docker:20.10-dind

default:
  tags:
    - kube

stages:
  - build
  - deploy

build:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint:
      - ""
  before_script:
    - mkdir -p /kaniko/docker
    - echo "{\"auths\":{\"${CI_REGISTRY}\":{\"auth\":\"$(printf "%s:%s" "${CI_REGISTRY_USER}" "${CI_REGISTRY_PASSWORD}" | base64 | tr -d '\n')\"}}}" > /kaniko/.docker/config.json
  script:
    - >-
      /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --destination "${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA}"
      --destination "${CI_REGISTRY_IMAGE}:latest"
  only:
    refs:
      - main

deploy_staging:
  stage: deploy
  before_script:
    - export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
    - export AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION
    - export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
    - aws eks update-kubeconfig --name brain-staging-cluster
  script:
    - kubectl -n app set image deployment/client-portal client-portal=registry.gitlab.com/luwjistik1/client-portal:${CI_COMMIT_SHA}
    - envsubst < ./.kubernetes/staging/configmap.yaml | kubectl -n app apply -f -
    - envsubst < ./.kubernetes/staging/deployment.yaml | kubectl -n app apply -f -
    - envsubst < ./.kubernetes/staging/ingress.yaml | kubectl -n app apply -f -
    - envsubst < ./.kubernetes/staging/service.yaml | kubectl -n app apply -f -
  only:
    refs:
      - main
