import { RootStateClientConnections } from '~/store/partnerPortals/clientConnections'

export interface VuexModuleClientConnections {
  partnerPortals: {
    clientConnections: RootStateClientConnections
  }
}

export interface Params {
  page: number
  perPage: number
  name: string
  status: string
}

export interface FilterClientConnections {
  name: string
  status: string
}

// Generated by https://quicktype.io

export interface Client {
  id: string
  name: string
  slug: string
}

export interface Partner {
  id: string
  name: string
  slug: string
  clientId: string
  status: string
  partnerServiceTypes: []
  partnerServiceZones: []
}

export interface ClientConnections {
  id: string
  clientId: string
  partnerId: string
  status: string
  partner: Partner
  client: Client
}
